# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0009_auto_20180521_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='triptaker',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='travelers',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
