# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0011_auto_20180521_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=8)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookings', models.ManyToManyField(related_name='trips', to='xapp.User')),
                ('tripmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='xapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='triptaker',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='travelers',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
