# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0012_auto_20180521_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tripmaker',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
