# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0016_auto_20180522_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bookings',
            field=models.ManyToManyField(related_name='joins', to='xapp.User'),
        ),
    ]
