# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0017_auto_20180522_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='xapp.User'),
        ),
    ]
