# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0018_auto_20180522_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planner',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
