# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0028_auto_20180523_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='wishlistadder',
        ),
        migrations.AddField(
            model_name='quote',
            name='adder',
            field=models.ManyToManyField(related_name='adds', to='xapp.User'),
        ),
    ]
