# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0031_auto_20180523_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quoter',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='adder',
        ),
        migrations.AddField(
            model_name='quote',
            name='booker',
            field=models.ManyToManyField(related_name='favoritequotes', to='xapp.User'),
        ),
    ]
