# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xapp', '0032_auto_20180524_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='booker',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
